
editor = 'nvim'
cursor = '▇'
blinking-cursor = true
theme = "tokyonight-storm"
padding-x = 10
option-as-alt = "both"

[window]
width = 1000
height = 800
mode = "Maximized"
decorations = "Enabled"
foreground-opacity = 1.0
background-opacity = 0.75
blur = true


[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = false

[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false

[fonts]
family = "Liga SFMono Nerd Font"
extras = [{ family = "Liga SFMono Nerd Font" }]
size = 16

[scroll]
multiplier = 5.0
divider = 1.0

[navigation]
mode = "Breadcrumb"
clickable = false
use-current-path = true
color-automation = []
