
editor = 'nvim'
cursor = '▇'
blinking-cursor = true
theme = "tokionights"
padding-x = 10
option-as-alt = "both"
# working-dir = "/Users/raphael/Documents/"
# env-vars = []
# use-fork = false

[window]
width = 1000
height = 800
mode = "Windowed"
foreground-opacity = 1.0
background-opacity = 0.7
blur = true
decorations = "Enabled"

[renderer]
performance = "Low"
backend = "Automatic"
disable-renderer-when-unfocused = false

[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false

[fonts]
   family = "MesloLGL Nerd Font Mono"
   size = 16

[scroll]
multiplier = 5.0
divider = 1.0

[navigation]
mode = "Breadcrumb"
clickable = false
use-current-path = true
color-automation = []

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-c", "/var/www"]


