VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

QMK_SETTINGS = yes
LTO_ENABLE = yes
